parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: 'sf_ceis_survey'
    database_user: root
    database_password: passIT42XKZ-0
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: paris9292
    database_path: null
