login:
    path:     /login
    defaults: { _controller: CeisSurveySecurityBundle:Security:login}
    
login_check:
    path:     /login_check
    
survey_users:
  resource: "@CeisSurveyUsersBundle/Resources/config/routing.yml"
  prefix: /survey/