parameters:
#    survey_users.example.class: Survey\Bundle\UsersBundle\Example

services:
#    survey_users.example:
#        class: %survey_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
