parameters:
#    girish_crud.example.class: Girish\Bundle\CrudBundle\Example

services:
#    girish_crud.example:
#        class: %girish_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
